# Generated by Django 5.2.15 on 2026-09-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(verbose_name='Mots-clés (séparés par des virgules)')),
                ('question_example', models.CharField(max_length=300, verbose_name='Question type')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Base de connaissance',
                'verbose_name_plural': 'Base de connaissances',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotUnknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question non reconnue')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question inconnue',
                'verbose_name_plural': 'Questions inconnues',
                'ordering': ['-created_at'],
            },
        ),
    ]
