# Generated by Django 5.2.15 on 2026-09-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Image')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='Badge (ex: -15%)')),
                ('badge_color', models.CharField(default='#C1121F', max_length=7, verbose_name='Couleur badge')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('advantages', models.TextField(blank=True, verbose_name='Avantages (un par ligne)')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotions.promotion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
