# Generated by Django 5.2.15 on 2026-06-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Féminin'), ('plusieurs', 'Plusieurs')], default='masculin', max_length=20, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('commercial', 'Commercial'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
