# Generated by Django 5.2.15 on 2026-09-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=60, unique=True, verbose_name='Référence')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie (m²)')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dossiers/', verbose_name='Photo du dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_proprietaire', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-est_proprietaire', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DossierCodeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtapeCochee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('date_auto_coche', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'étape")),
                ('type', models.CharField(choices=[('technique', 'Technique'), ('morcellement', 'Morcellement')], max_length=20, verbose_name='Type')),
                ('percentage', models.PositiveIntegerField(verbose_name='Pourcentage (%)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('description', models.TextField(blank=True, verbose_name='Description (HTML autorisé)')),
                ('duree_jours', models.PositiveIntegerField(default=7, help_text='Nombre de jours avant passage automatique à cette étape')),
            ],
            options={
                'verbose_name': 'Étape globale',
                'verbose_name_plural': 'Étapes globales',
                'ordering': ['type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IntituleDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='intitules/', verbose_name='Image de fond')),
            ],
            options={
                'verbose_name': 'Intitulé de dossier',
                'verbose_name_plural': 'Intitulés de dossier',
                'ordering': ['name'],
            },
        ),
    ]
