# Generated by Django 5.2.15 on 2026-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dossiers/', verbose_name='Photo du dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie (m²)'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='reference',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='etapeglobale',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
