# Generated by Django 5.2.15 on 2026-09-21 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossieracces',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='dossieracces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_acces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossiercodeacces',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_acces', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='dossiercodeacces',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_acces_dossier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossierhistorique',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossierhistorique',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='etapecochee',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etapecochee',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_cochees', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='etapecochee',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.etapeglobale'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='intitule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dossiers.intituledossier', verbose_name='Intitulé'),
        ),
        migrations.AlterUniqueTogether(
            name='dossieracces',
            unique_together={('dossier', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='etapecochee',
            unique_together={('dossier', 'etape')},
        ),
    ]
