# Generated by Django 5.2.15 on 2026-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_dossier_date_paiement_dossier_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecochee',
            name='date_auto_coche',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de cochage automatique prévu'),
        ),
    ]
