# Generated by Django 5.2.15 on 2026-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_etapecochee_date_auto_coche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapecochee',
            name='date_auto_coche',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date cochage auto prévue'),
        ),
        migrations.AlterField(
            model_name='etapeglobale',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description (HTML autorisé)'),
        ),
    ]
