# Generated by Django 5.2.15 on 2026-06-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_alter_etapecochee_date_auto_coche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntituleDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Intitulé de dossier',
                'verbose_name_plural': 'Intitulés de dossier',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='property_link',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='title',
        ),
        migrations.AlterField(
            model_name='etapecochee',
            name='date_auto_coche',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='intitule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dossiers.intituledossier', verbose_name='Intitulé'),
        ),
    ]
