# Generated by Django 5.2.15 on 2026-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_intituledossier_remove_dossier_property_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapecochee',
            options={},
        ),
        migrations.AddField(
            model_name='intituledossier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='intitules/', verbose_name='Image de fond'),
        ),
    ]
