# Generated by Django 5.2.15 on 2026-06-24 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_alter_etapecochee_options_intituledossier_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_proprietaire', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='dossiers.dossier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_acces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-est_proprietaire', 'date_ajout'],
                'unique_together': {('dossier', 'user')},
            },
        ),
    ]
