# Generated by Django 5.2.15 on 2026-06-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_dossieracces'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierCodeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(blank=True, help_text='Ex: Nom de la personne concernée', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_acces', to='dossiers.dossier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
