# Generated by Django 5.2.15 on 2026-06-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_dossiercodeacces'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeglobale',
            name='duree_jours',
            field=models.PositiveIntegerField(default=7, help_text='Nombre de jours avant passage automatique à cette étape'),
        ),
    ]
