# Generated by Django 5.2.15 on 2026-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_dossiercodeacces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intituledossier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
