# Generated by Django 5.2.15 on 2026-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0011_alter_dossier_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='intituledossier',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
